#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = XfToolkit\Console\Application::start();

$app->registerServices(
	new XfToolkit\Tools\ToolsServiceProvider,
	//new XfToolkit\FileSync\FileSyncServiceProvider,
	new XfToolkit\AddOn\AddOnServiceProvider,
	new XfToolkit\Build\BuildServiceProvider
);

$app->run();