#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = XfToolkit\Toolkit::start();

$commands = [
	'XfToolkit\Commands\SelfUpdate',
];

$app->resolveCommands($commands);

$app->run();
